site_name:        mod_swift
site_url:         http://mod-swift.org/
site_author:      ZeeZide GmbH
repo_url:         https://github.com/modswift/
google_analytics: [ 'UA-3266252-11', 'mod-swift.org' ]
  
docs_dir:    content
site_dir:    docs

theme:       readthedocs

pages:
  - 'Introduction': 'index.md'
  - 'About':        'about.md'
  