site_name:        mod_swift
site_url:         http://mod-swift.org/
site_author:      ZeeZide GmbH
repo_url:         https://github.com/modswift/
google_analytics: [ 'UA-3266252-11', 'mod-swift.org' ]
  
docs_dir:    content
site_dir:    docs

theme:       readthedocs
extra_css:   [ extra.css ]

pages:
  - 'Introduction':            'index.md'
  - 'Installation':            'install.md'
  - 'Using mod_swift':         'usage.md'
  - 'Configuration Templates': 'configtemplates.md'
  - 'Tools Reference':         'tools.md'
  - 'ApacheExpress':           'apacheexpress.md'
  - 'HTTP/2':                  'http2.md'
  - 'SQL Database Access':     'mod_dbd.md'
  - 'Link Collection':         'links.md'
  - 'About':                   'about.md'
